#!/usr/bin/env bash

APP_NAME="Fix Chrome Apps"
DESCRIPTION="Fix Chrome apps Icons"
DIR="${HOME}/Applications/fix-chrome-apps"
START_FILE="index.js"
ICON_FILE="fix-chrome-apps/icon.png"
ICON_PATH="${HOME}/.local/share/applications/fix-chrome-apps.desktop"

BASEDIR=$(dirname $0)
cd ${BASEDIR}

if [[ ! -d ${DIR} ]]; then
    mkdir -p ${DIR}
    cp -r ${BASEDIR}/* ${DIR}
fi

ICON="[Desktop Entry]\n\
Name=${APP_NAME}\n\
Comment=${DESCRIPTION}\n\
Exec=${DIR}/start\n\
TryExec=${DIR}/start\n\
Icon=${DIR}/${ICON_FILE}\n\
Terminal=false\n\
Type=Application\n\
StartupWMClass=${START_FILE}"

echo -e ${ICON} > ${ICON_PATH}
zenity --info --title="Instalado com sucesso!" --text="${APP_NAME} instalado com sucesso!\n\nInstalado em: ${DIR}." --width="300" height="50"
